language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r ./test/requirements.txt
# command to run tests
script:
  - python project/tests #python setup.py nosetests # or py.test for Python versions 3.5 and below
#after_success:
#  - coveralls