version: "3.2"
services:
  generator:
    build: .
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
  test:
    build: test
    volumes:
      - type: bind
        source: .
        target: /usr/src/app