version: "3.2"
services:
  csv-gen:
    build: .
    volumes:
    - .:/usr/src/app

  csv-gen-dev:
    build: .
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
  test:
    build: test
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
    command: ["coverage", "run", "setup.py", "test"]